<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ingat saya__3gRWUe4J-cmzr2kvWllrU1</name>
   <tag></tag>
   <elementGuidId>f406e588-4584-4157-9fe7-94fe00874b16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div/div/div/div/div/form/section[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._3gRWUe4J-cmzr2kvWllrU1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3gRWUe4J-cmzr2kvWllrU1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;GO9ukF5A0Q3PLYs7W5g7N&quot;]/div[@class=&quot;container flex flex-col md:flex-row justify-center items-center mx-auto h-screen&quot;]/div[@class=&quot;px-2 w-full md:w-auto flex flex-col md:h-full justify-center&quot;]/div[@class=&quot;card w-auto _20XA_3KoZzXhNRzUWepDvv&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;_9yz4OCIfTxlZZ-4tjpF8t  h-full&quot;]/div[@class=&quot;w-full&quot;]/form[@class=&quot;_3HCPc_mMHJ3JFeiPOa9h9d&quot;]/section[@class=&quot;T7_c5mnw4164G-CyTQQwz&quot;]/div[@class=&quot;_3gRWUe4J-cmzr2kvWllrU1&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/div/div/form/section[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingat saya'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa password?'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
