<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hapus_file</name>
   <tag></tag>
   <elementGuidId>a96496bc-cc44-47bf-ae55-fa6afb8bcf01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img._1as0_9Xxeat8WfmVNOFwqo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/main/div/div/div[2]/div/form/div[9]/div[2]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1as0_9Xxeat8WfmVNOFwqo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://minio-storage-core-tribe-edu-dev.vsan-apps.playcourt.id/web-assets/assets/ic_close.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/main[@class=&quot;aNWPbcduxteqYl7DfDJiY&quot;]/div[@class=&quot;container mx-auto&quot;]/div[1]/div[@class=&quot;T4JDmDttmS4-YX7brj9sg&quot;]/div[@class=&quot;flex flex-col justify-center mt-5 lg:ml-20&quot;]/form[1]/div[@class=&quot;_1x_jxFFLnxSx5PqyFrXUeP&quot;]/div[@class=&quot;KLKnzjPocKD00kxcZhXi7&quot;]/div[@class=&quot;jT5YTm3YvSSNxoShM8DNr&quot;]/div[@class=&quot;border-dashed border-2 p-4 border-gray-500&quot;]/div[@class=&quot;flex&quot;]/img[@class=&quot;_1as0_9Xxeat8WfmVNOFwqo&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/div/div[2]/div/form/div[9]/div[2]/div/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://minio-storage-core-tribe-edu-dev.vsan-apps.playcourt.id/web-assets/assets/ic_close.svg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
