<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div___25JKTDiGAsl_gfWaijz06K</name>
   <tag></tag>
   <elementGuidId>91c1d46f-67fd-48d9-a655-fcf1a0627cf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;swal2-content&quot;)/div[@class=&quot;relative py-2 flex-auto -mx-5 my-4&quot;]/div[@class=&quot;py-1&quot;]/div[@class=&quot;_1HDOMJX-osTRXqGO-3wBjX text-gray-700 hover:text-white cursor-pointer&quot;]/form[1]/label[1]/div[@class=&quot;_25JKTDiGAsl_gfWaijz06K&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._25JKTDiGAsl_gfWaijz06K</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swal2-content']/div/div[2]/div[2]/form/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_25JKTDiGAsl_gfWaijz06K</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-content&quot;)/div[@class=&quot;relative py-2 flex-auto -mx-5 my-4&quot;]/div[@class=&quot;py-1&quot;]/div[@class=&quot;_1HDOMJX-osTRXqGO-3wBjX text-gray-700 hover:text-white cursor-pointer&quot;]/form[1]/label[1]/div[@class=&quot;_25JKTDiGAsl_gfWaijz06K&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swal2-content']/div/div[2]/div[2]/form/label/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
   </webElementXpaths>
</WebElementEntity>
